##数据库连接设置
spring:
  datasource:
    url: jdbc:h2:mem:test_db;DATABASE_TO_UPPER=false;MODE=MYSQL;
    platform: h2
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    username: root
    password: password
  h2:
    console:
      enabled: true

server:
  port: 8044

logging:
  level:
    root: info
    com.shenjies88.practice.h2practice: debug

